### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by interstateone** [krzysztofzablocki/Versionable#1]
Hey! I like the concept that you [wrote about](http://merowing.info/2020/06/adding-support-for-versioning-and-migration-to-your-codable-models./) and demonstrated here. I was considering using it but it appears that there isn't an open source license specified in the blog post or repo. I see most of your other repos are using MIT, do you think you could add that here too? Thanks :)

**Comment by krzysztofzablocki** [comment]
sure thing, I always use MIT I'll add it in a sec

**Comment by krzysztofzablocki** [comment]
done

**Comment by interstateone** [comment]
Thank you! 😄
